const CONTENT = {
  en: {
    nav_logo: "ASAPTIC LABS",
    nav_link1: "Crossings",
    nav_link2: "Work",
    nav_link3: "Contact",
    nav_cta: "Talk to us",
    hero_eyebrow: "AI AGENTS AT THE CROSSINGS",
    hero_title: "Where the decision is irreversible, we make the agent accountable.",
    hero_sub: "Quantum security. Physical systems. Human care.",
    hero_cta: "See our work →",
    crossings_label: "THREE CROSSINGS",
    q_tag: "× QUANTUM SECURITY",
    q_heading: "Quantum Security",
    q_body: "Quantum computing will break today's encryption. Every enterprise has one window to migrate — and getting it wrong is permanent. We build AI agents that assess, plan, and execute cryptographic transitions before that window closes.",
    hw_tag: "× PHYSICAL SYSTEMS",
    hw_heading: "Physical Systems",
    hw_body: "Drones, robots, and autonomous machines act in the real world. There is no undo. We build agents with embedded decision logic and hard constraints — so when the system acts, it acts with accountability baked in.",
    care_tag: "× HUMAN CARE",
    care_heading: "Human Care",
    care_body: "We operate inside 200+ eldercare and clinical institutions. These environments are regulated, trust-constrained, and unforgiving of errors. Our agents support care workers without replacing their judgment — and every interaction is auditable.",
    thread_heading: "Every correction teaches the next deployment.",
    thread_body: "Every decision our agents make is logged. When a human overrides it — in a security audit, a field operation, or a care round — that correction becomes training data. The system learns from the crossing, not from a benchmark. Across quantum, hardware, and care, one principle holds: the agent gets smarter where the stakes are highest.",
    ops_label: "HOW WE OPERATE",
    ops_heading: "We run on what we build.",
    ops_body: "Asaptic Labs is AI-operated. Our daily operations, architecture reviews, and strategic briefings run on the same accountability backbone we deploy for clients. Every internal AI decision is logged, escalated, and corrected the same way. We are our own first deployment.",
    ops_coo: "AI COO",
    ops_coo_desc: "Operations, scheduling, and daily execution managed by AI agents with full audit trail.",
    ops_cto: "AI CTO",
    ops_cto_desc: "Architecture decisions reviewed by AI with reversibility scoring on every material change.",
    ops_operator: "AI Operator",
    ops_operator_desc: "Cross-session memory, briefings, and task continuity maintained by persistent AI agents.",
    footer_logo: "Asaptic Labs",
    footer_link1: "Crossings",
    footer_link2: "Work",
    footer_link3: "Contact",
    footer_link4: "Privacy",
    footer_tagline: "AI agents built for decisions that matter.",
    footer_copyright: "© 2026 Asaptic Labs"
  },
  zh: {
    nav_logo: "ASAPTIC LABS",
    nav_link1: "关键领域",
    nav_link2: "工作成果",
    nav_link3: "联系我们",
    nav_cta: "与我们交流",
    hero_eyebrow: "关键决策中的AI智能体",
    hero_title: "在不可逆的决策节点，我们让智能体承担责任。",
    hero_sub: "量子安全。物理系统。人文关怀。",
    hero_cta: "查看我们的工作 →",
    crossings_label: "三大关键领域",
    q_tag: "× 量子安全",
    q_heading: "量子安全",
    q_body: "量子计算将会破解当今的加密体系。每家企业只有一次迁移窗口——而一旦出错，后果将无法挽回。我们构建AI智能体，在窗口关闭之前完成密码学迁移的评估、规划与执行。",
    hw_tag: "× 物理系统",
    hw_heading: "物理系统",
    hw_body: "无人机、机器人和自主机器在现实世界中行动，没有撤销的机会。我们构建嵌入决策逻辑与硬性约束的智能体——让系统的每一次行动都内置问责机制。",
    care_tag: "× 人文关怀",
    care_heading: "人文关怀",
    care_body: "我们在200余家养老及医疗机构中运营。这些环境受到严格监管，信任边界清晰，对错误零容忍。我们的智能体协助护理人员，而非取代其判断——每一次交互均可审计。",
    thread_heading: "每一次纠正，都在教会下一次部署。",
    thread_body: "智能体的每一个决策都有记录。当人工干预覆盖它——无论是在安全审计、现场操作还是护理巡查中——这次纠正就会转化为训练数据。系统从真实决策节点中学习，而非从基准测试中学习。跨越量子、硬件与关怀三大领域，一个原则始终成立：风险越高，智能体越聪明。",
    ops_label: "我们如何运营",
    ops_heading: "我们在自己的产品上运行。",
    ops_body: "Asaptic Labs 采用AI驱动运营模式。我们的日常运营、架构审查和战略简报，均运行在我们为客户部署的同一套问责骨干系统之上。每一个内部AI决策都以同样的方式被记录、上报和纠正。我们是自己的第一个部署客户。",
    ops_coo: "AI 首席运营官",
    ops_coo_desc: "运营、调度与日常执行由AI智能体管理，并留有完整审计记录。",
    ops_cto: "AI 首席技术官",
    ops_cto_desc: "架构决策由AI审查，每项重大变更均有可逆性评分。",
    ops_operator: "AI 运营官",
    ops_operator_desc: "跨会话记忆、简报及任务连续性由持久化AI智能体维护。",
    footer_logo: "Asaptic Labs",
    footer_link1: "关键领域",
    footer_link2: "工作成果",
    footer_link3: "联系我们",
    footer_link4: "隐私政策",
    footer_tagline: "为真正重要的决策而构建的AI智能体。",
    footer_copyright: "© 2026 Asaptic Labs"
  },
  zht: {
    nav_logo: "ASAPTIC LABS",
    nav_link1: "關鍵領域",
    nav_link2: "工作成果",
    nav_link3: "聯絡我們",
    nav_cta: "與我們傾談",
    hero_eyebrow: "關鍵決策中的AI智能體",
    hero_title: "在不可逆的決策節點，我們讓智能體承擔責任。",
    hero_sub: "量子安全。實體系統。人文關懷。",
    hero_cta: "查看我們的工作 →",
    crossings_label: "三大關鍵領域",
    q_tag: "× 量子安全",
    q_heading: "量子安全",
    q_body: "量子運算將瓦解現有的加密體系。每間企業只有一次遷移窗口——一旦出錯，後果將無法挽回。我們構建AI智能體，在窗口關閉之前完成密碼學遷移的評估、規劃與執行。",
    hw_tag: "× 實體系統",
    hw_heading: "實體系統",
    hw_body: "無人機、機械人及自主機器在現實世界中行動，沒有撤銷的機會。我們構建內嵌決策邏輯與硬性限制的智能體——讓系統每一次行動都具備問責機制。",
    care_tag: "× 人文關懷",
    care_heading: "人文關懷",
    care_body: "我們於200多間安老及醫療機構中運作。這些環境受嚴格監管，信任邊界清晰，對錯誤零容忍。我們的智能體輔助護理人員，而非取代其判斷——每一次互動均可審計。",
    thread_heading: "每一次糾正，都在教會下一次部署。",
    thread_body: "智能體的每一個決策均有記錄。當人工介入覆蓋它——無論是在安全審計、現場行動還是護理巡查中——這次糾正便會轉化為訓練數據。系統從真實決策節點中學習，而非從基準測試中學習。橫跨量子、硬件與關懷三大領域，一個原則始終成立：風險愈高，智能體愈聰明。",
    ops_label: "我們如何運營",
    ops_heading: "我們在自己的產品上運行。",
    ops_body: "Asaptic Labs 採用AI驅動運營模式。我們的日常運營、架構審查和戰略簡報，均運行在我們為客戶部署的同一套問責骨幹系統之上。每一個內部AI決策都以同樣的方式被記錄、上報和糾正。我們是自己的第一個部署客戶。",
    ops_coo: "AI 行政總裁（運營）",
    ops_coo_desc: "運營、調度與日常執行由AI智能體管理，並留有完整審計記錄。",
    ops_cto: "AI 首席技術官",
    ops_cto_desc: "架構決策由AI審查，每項重大變更均有可逆性評分。",
    ops_operator: "AI 運營官",
    ops_operator_desc: "跨對話記憶、簡報及任務連續性由持久化AI智能體維護。",
    footer_logo: "Asaptic Labs",
    footer_link1: "關鍵領域",
    footer_link2: "工作成果",
    footer_link3: "聯絡我們",
    footer_link4: "私隱政策",
    footer_tagline: "為真正重要的決策而構建的AI智能體。",
    footer_copyright: "© 2026 Asaptic Labs"
  }
};
