const CONTENT = {
  en: {
    nav_physical: "Physical AI",
    nav_sourcing: "Sourcing",
    nav_watchlist: "Watchlist",
    nav_engage: "Engage",
    nav_blog: "Blog",
    nav_cta: "Contact",
    hero_eyebrow: "PHYSICAL AI · DRONE / MARINE / ROBOT",
    hero_title: "Physical AI for drones, marine, and robots.",
    hero_sub: "Asaptic builds embodied autonomous systems across the air, sea, and ground — the HK300 heavy-lift unmanned helicopter, autonomous marine vessels, and ground robots. An HKU DeepTech 100 startup, incubated in the HKSTP ecosystem.",
    hero_primary: "Partner with us",
    hero_secondary: "View domains",
    hero_panel_status: "SYSTEMS MAP ACTIVE",
    map_aerial: "Aerial",
    map_marine: "Marine",
    map_ground: "Ground",
    metric_weight: "300kg",
    metric_weight_label: "HK300 validated platform",
    metric_domains: "3",
    metric_domains_label: "physical domains",
    metric_response: "<4h",
    metric_response_label: "response promise",
    physical_label: "L0 / PHYSICAL AI FRONTIER",
    physical_title: "Embodied autonomy across air, sea, and ground.",
    physical_intro: "Asaptic builds the control, deployment, and trust layer for autonomous machines that operate in the real world — embodied intelligence across air, sea, and ground.",
    aerial_tag: "AERIAL SYSTEMS",
    aerial_heading: "Heavy-lift unmanned coaxial helicopters and drones.",
    aerial_body: "The aerial domain starts with HK300: a validated 300kg heavy-lift unmanned coaxial helicopter platform for industrial payloads, field logistics, and mission-specialized autonomy.",
    aerial_spec1: "HK300",
    aerial_spec2: "coaxial / unmanned",
    marine_tag: "MARINE AUTONOMY",
    marine_heading: "Autonomous surface and underwater vessels.",
    marine_body: "Marine systems extend the same embodied-AI stack into inspection, environmental monitoring, port operations, and endurance missions above and below the surface.",
    marine_spec1: "USV / UUV",
    marine_spec2: "navigation / sensing",
    ground_tag: "GROUND ROBOTS",
    ground_heading: "Robots for logistics, inspection, and field work.",
    ground_body: "Ground robots close the physical loop: mobility, manipulation, perception, fleet orchestration, and human-supervised autonomy for sites where software alone cannot act.",
    ground_spec1: "mobile robots",
    ground_spec2: "fleet operations",
    srcpage_eyebrow: "CHINA DEEP-TECH SOURCING GATEWAY",
    srcpage_title: "The trust layer between China's deep-tech and the world.",
    srcpage_sub: "Asaptic connects factories directly to Western and Global-South buyers — carrying the compliance, certification, QA, and accountability that turns sourcing into a margin you can defend.",
    l1_label: "L1 / CHINA DEEP-TECH SOURCING GATEWAY",
    l1_title: "Direct factory to Western end-buyer, with the missing trust layer.",
    l1_intro: "China deep-tech supply connected to serious Western and Global-South buyers. Asaptic earns the margin by providing the trust layer middlemen never did — supplier diligence, CE / FDA and destination-market certification (GCC, INMETRO, SONCAP), QA inspection with optional visual factory verification, and accountable delivery. For export-sensitive components, supply is screened for clean, non-US-IP technology origin.",
    l1_cta: "Start an RFQ →",
    flow_factory: "China factory",
    flow_asaptic: "Asaptic trust / QA / compliance",
    flow_buyer: "Western end-buyer",
    cat_energy: "Energy",
    cat_energy_body: "Solar, BESS, and inverters. ",
    cat_energy_link: "Focus on UFLPA traceability and UL 9540A certification.",
    cat_energy_ev: "EV charger power modules (SiC)",
    cat_medical: "Medical devices",
    cat_medical_body: "Clinically credible sourcing backed by a clinical-authority partner and frontline healthcare context.",
    cat_components: "Deep-tech components",
    cat_components_body: "Sensors, robotics parts, photonics, power electronics, and mission-specific assemblies.",
    l2_label: "L2 / R&D WATCHLIST",
    l2_title: "Trade now. Build later. Compound the equity.",
    l2_intro: "L2 is the spear: a focused watchlist of China deep-tech fields where sourcing relationships can become technical insight, distribution leverage, and eventually product equity.",
    watch_tfln: "TFLN / LiNbO3 photonics and RF filters",
    watch_tfln_body: "Priority number one: thin-film lithium niobate for high-speed photonics, RF front ends, and next-generation signal infrastructure.",
    watch_gan: "GaN power",
    watch_gan_body: "Wide-bandgap power electronics for robotics, energy conversion, charging, and compact high-efficiency systems.",
    watch_perovskite: "Perovskite",
    watch_perovskite_body: "High-upside solar materials and manufacturing transitions that may reshape distributed energy economics.",
    watch_cooling: "AI liquid-cooling",
    watch_cooling_body: "Thermal infrastructure for dense AI compute, data centers, and edge deployments.",
    watch_sodium: "Na-ion batteries",
    watch_sodium_body: "Cost-sensitive storage chemistry for grid, mobility, and supply-chain-resilient energy systems.",
    watch_lidar: "LiDAR",
    watch_lidar_body: "Perception hardware for autonomy across aerial, marine, ground, and industrial inspection systems.",
    authority_label: "AUTHORITY MOAT",
    authority_title: "Hong Kong credibility wrapped around China execution.",
    authority_intro: "The defensibility is not only sourcing access. It is the trust/compliance layer: clinical authority, university and science-park context, and state-affiliated trade access packaged for serious buyers.",
    authority_hku: "Academic and Hong Kong research context through HKU relationships.",
    authority_hkstp: "Science-park signal and deep-tech ecosystem proximity.",
    authority_clinical: "Clinical authority, eldercare operations, and medical-device buyer credibility.",
    engage_label: "ENGAGE",
    engage_title: "Tell us what you need. We answer in under four hours.",
    engage_body: "Send us your project, requirements, and timeline. We will come back with a clear path and the concrete next step.",
    eco_label: "RECOGNITION & ECOSYSTEM",
    eco_title: "An HKU DeepTech 100 startup, incubated at HKSTP.",
    eco_intro: "Asaptic is built inside Hong Kong's deep-tech engine — selected for the University of Hong Kong's DeepTech 100 program and incubated within the Hong Kong Science and Technology Parks ecosystem.",
    eco_card1: "HKU DeepTech 100",
    eco_card1_desc: "Selected for the University of Hong Kong's DeepTech 100 program — university research linkage and a deep-tech founder network.",
    eco_card2: "HKSTP Incubation",
    eco_card2_desc: "Incubated within the Hong Kong Science and Technology Parks ecosystem — engineering, lab, and ecosystem support for embodied-AI development.",
    engage_cta: "engage@asaptic.com",
    footer_thesis: "Thesis",
    footer_engage: "Engage",
    footer_press: "Press",
    footer_privacy: "Privacy",
    footer_tagline: "China deep-tech, traded with Western-grade trust.",
    footer_tagline_home: "Embodied autonomous systems for air, sea, and ground.",
    footer_copy: "© 2026 Asaptic",
    bess_hero_eyebrow: "CLEAN-CHAIN ENERGY STORAGE",
    bess_hero_title: "UFLPA & UL 9540A: The 2026 Standard for BESS Sourcing.",
    bess_hero_sub: "In 2026, sourcing BESS from China is no longer about finding a factory — it is about Customs Clearance and Fire Safety. Asaptic provides the technical gatekeeping to land high-capacity LFP systems without regulatory seizure.",
    bess_uflpa_label: "UFLPA TRACEABILITY",
    bess_uflpa_title: "Beyond the \"Sanitized\" Bill of Lading.",
    bess_uflpa_intro: "CBP seizures are at an all-time high. U.S. Customs now requires raw material traceability down to the lithium mine and quartzite source. Our \"Clean-Chain\" protocol audits Tier-1 sources outside restricted regions and provides HK-escrowed documentation before shipment.",
    bess_cell_title: "Grade-A Cell Verification",
    bess_cell_body: "We only source systems using verifiable Grade-A LFP cells from CATL, BYD, and EVE. No repurposed or Grade-B cells.",
    bess_safety_title: "UL 9540A Safety",
    bess_safety_body: "NRTL-verified thermal runaway protection and fire suppression hardware for US C&I project permitting.",
    bess_audit_label: "THE ASAPTIC 12-POINT AUDIT",

    src_title: "China Deep-Tech & Certified Components Sourcing",
    src_sub: "Factory-direct supply from verified Chinese manufacturers to Western B2B principals. Full compliance documentation. Backed by our cross-standard database spanning 854 compliance comparisons across 169 destination markets. Deposit-secured production slots. Six active sourcing lanes — from clinical devices to energy storage to Physical-AI components.",
    src_tag1: "Health Canada · TGA Certified",
    src_h1: "Clinical Devices",
    src_p1: "Bioimpedance and body-composition analyzers for hospital and aged-care procurement in Canada and Australia. MDALL + ARTG factory verification. 5-step certified sourcing process.",
    src_l1: "Clinical Device Sourcing →",
    src_tag2: "Scarce Supply · 5-Day Sample",
    src_h2: "Photonics — TFLN",
    src_p2: "Thin-film lithium niobate wafers and electro-optic modulators sourced directly from qualified Chinese foundries. In-stock 4\" and 6\" wafers. Sample orders fulfilled within 5 business days.",
    src_l2: "TFLN Sourcing →",
    src_tag3: "Deposit-First · 30% PI",
    src_h3: "How It Works",
    src_p3: "30% proforma deposit reserves a certified factory's production slot. Balance against Bill of Lading. Full compliance document package at shipment. Transparent process — no grey market.",
    src_l3: "Our Process →",
    src_tag4: "BESS · Inverters · EV Chargers",
    src_h4: "Energy Systems",
    src_p4: "Solar inverters, battery energy storage systems (BESS), and EV charging modules from UFLPA-compliant Chinese factories. CE, UL, and IEC-certified supply chains with full traceability documentation for Western grid and mobility markets.",
    src_l4: "Energy Sourcing →",
    src_tag5: "GaN · Na-ion · Thermal",
    src_h5: "Deep-Tech Components",
    src_p5: "GaN power electronics, sodium-ion battery cells, and advanced cold-plate thermal management modules sourced from China's deep-tech manufacturing cluster. Ideal for power conversion, next-gen energy storage, and high-density compute cooling.",
    src_l5: "Deep-Tech Sourcing →",
    src_tag6: "Actuators · E-Skin · RPM",
    src_h6: "Physical-AI & Robotics",
    src_p6: "Precision actuators, electronic-skin sensor arrays, and robotic perception modules (RPM) for embodied-AI and humanoid robot integrators. Factory-direct from China's emerging Physical-AI component ecosystem — vetted for Western OEM qualification.",
    src_l6: "Robotics Components →",
    src_l7: "Explore all sourcing lanes →",
    src_l8: "Factory-direct vs trading company: what buyers need to know →",
    nav_agents: "Agents",
    agents_portal_cta: "Portal →",
    agents_eyebrow: "ASAPTIC AGENTS — AI PLATFORM FOR GREATER-CHINA COMPANIES",
    agents_title: "Form. Comply. Fund. Scale globally.",
    agents_sub: "Asaptic Agents is the AI agent platform that handles the full company lifecycle for Greater-China companies going global — from day-one incorporation to ongoing compliance, government funding, and cross-border sourcing and export.",
    agents_hero_cta: "Access the portal →",
    agents_hero_secondary: "Request early access",
    agents_lineup_label: "THE AGENT LINEUP",
    agents_lineup_title: "One platform. Four domains. Every stage of the journey.",
    agents_lineup_intro: "Each agent is purpose-built for one phase of the Greater-China-to-global company lifecycle. They share a single portal, a single memory, and a single compliance backbone — so context flows automatically from formation to funding to export.",
    agent_form_tag: "FORMATION AGENT",
    agent_form_title: "Company Formation",
    agent_form_body: "Incorporates a Hong Kong, BVI, or Cayman entity, selects the optimal holding structure for your capital raising goals, drafts constitutional documents, and wires in the bank account and registered-address infrastructure — in days, not weeks.",
    agent_comply_tag: "COMPLIANCE AGENT",
    agent_comply_title: "Regulatory Compliance",
    agent_comply_body: "Monitors annual return deadlines, NAR1 filings, tax obligations, and destination-market regulatory requirements. Drafts filings, flags approaching deadlines, and keeps the corporate record current across every jurisdiction your company operates in.",
    agent_fund_tag: "FUNDING AGENT · LIVE",
    agent_fund_title: "R&D Funding Discovery",
    agent_fund_body: "Scans Hong Kong InnoFund, HKPC, ITC, and other government grant programmes daily. Matches your company profile to open calls, drafts the application, and tracks submission deadlines — so you never miss a funding window.",
    agent_fund_link: "Activate in portal →",
    agent_tender_tag: "TENDER AGENT · LIVE",
    agent_tender_title: "Government Tender Response",
    agent_tender_body: "Monitors PCMS (HK Government's procurement system) for matching tenders, scores fit against your capabilities, drafts the full response package — technical, commercial, and compliance sections — and tracks submission.",
    agent_tender_link: "Activate in portal →",
    agent_export_tag: "SOURCING-EXPORT AGENT",
    agent_export_title: "Cross-Border Sourcing & Export",
    agent_export_body: "Connects your company's products to Western and Global-South buyers — managing RFQ intake, supplier diligence, certification packaging (CE, FDA, GCC, INMETRO), QA inspection, and accountable delivery. Powered by the Asaptic China deep-tech sourcing gateway.",
    agent_export_link: "See the sourcing gateway →",
    agents_flywheel_label: "THE LIFECYCLE FLYWHEEL",
    agents_flywheel_title: "Every stage feeds the next.",
    agents_flywheel_intro: "Asaptic Agents treats the company lifecycle as a compounding loop — formation unlocks compliance, compliance unlocks funding, funding unlocks growth, growth unlocks export. The agents share context across every stage so nothing falls through the cracks.",
    fly_form: "Form",
    fly_form_body: "Incorporate the right entity in the right jurisdiction. Corporate record established from day one.",
    fly_comply: "Comply",
    fly_comply_body: "Annual returns, tax filings, and destination-market regulations tracked and filed automatically.",
    fly_fund: "Fund",
    fly_fund_body: "Government grants and tenders discovered, matched, drafted, and submitted — continuously.",
    fly_grow: "Grow Global",
    fly_grow_body: "Products sourced and exported to Western and Global-South markets with full compliance and QA.",
    agents_live_label: "LIVE TODAY",
    agents_live_title: "Two agents already running. More in the pipeline.",
    agents_live_intro: "The R&D Funding Agent and Tender Agent are operational inside the Asaptic portal. They run daily scans, draft responses, and surface matches automatically — no manual monitoring required.",
    live_fund_label: "R&D Funding",
    live_fund_body: "Daily scans of HK InnoFund, HKPC, ITC, and allied grant programmes. Matches open. Applications drafted.",
    live_tender_label: "PCMS Tenders",
    live_tender_body: "Monitors HK Government's PCMS procurement system. Scores fit. Drafts full tender response packages.",
    live_portal_label: "Portal Access",
    live_portal_body: "All agents run through portal.asaptic.com. Request early access for agents not yet in the portal.",
    agents_cta_label: "GET STARTED",
    agents_cta_title: "Your company lifecycle, running on agents.",
    agents_cta_body: "Access the portal to activate the live agents, or contact us to discuss a custom agent deployment for your Greater-China company.",
    agents_cta_portal: "Open portal →",
    agents_cta_email: "engage@asaptic.com",
  },
  zh: {
    nav_physical: "物理 AI",
    nav_sourcing: "采购",
    nav_watchlist: "观察名单",
    nav_engage: "参与",
    nav_blog: "博客",
    nav_cta: "联系我们",
    hero_eyebrow: "物理 AI · 无人机 / 海事 / 机器人",
    hero_title: "为无人机、海事和机器人打造的物理 AI。",
    hero_sub: "Asaptic 跨越空、海、陆三域构建具身自主系统 —— 包括 HK300 重载无人共轴直升机平台、自主海事船只和陆地机器人。香港大学 DeepTech 100 入选初创，孵化于香港科技园生态。",
    hero_primary: "与我们合作",
    hero_secondary: "查看领域",
    hero_panel_status: "系统地图已激活",
    map_aerial: "航空",
    map_marine: "海事",
    map_ground: "陆地",
    metric_weight: "300kg",
    metric_weight_label: "HK300 已验证平台",
    metric_domains: "3",
    metric_domains_label: "物理领域",
    metric_response: "<4h",
    metric_response_label: "响应承诺",
    physical_label: "L0 / 物理 AI 前沿",
    physical_title: "空、海、陆三域的具身自主。",
    physical_intro: "Asaptic 为在现实世界中运行的自主机器构建控制、部署与信任层——贯穿空、海、陆的具身智能。",
    aerial_tag: "航空系统",
    aerial_heading: "重载无人共轴直升机和无人机。",
    aerial_body: "航空领域始于 HK300：一个经过验证的 300 公斤级重载无人共轴直升机平台，用于工业载荷、野外物流和任务专用自主系统。",
    aerial_spec1: "HK300",
    aerial_spec2: "共轴 / 无人",
    marine_tag: "海事自主",
    marine_heading: "自主水面和水下船只。",
    marine_body: "海事系统将同样的具身 AI 技术栈延伸到水面和水下的巡检、环境监测、港口运营和长航时任务。",
    marine_spec1: "USV / UUV",
    marine_spec2: "导航 / 传感",
    ground_tag: "陆地机器人",
    ground_heading: "用于物流、巡检和野外工作的机器人。",
    ground_body: "陆地机器人闭合了物理环路：移动性、操作性、感知、车队编排以及针对软件无法行动的现场提供人类监督的自主性。",
    ground_spec1: "移动机器人",
    ground_spec2: "车队运营",
    srcpage_eyebrow: "中国深科技采购网关",
    srcpage_title: "中国深科技与世界之间的信任层。",
    srcpage_sub: "Asaptic 将工厂直接连接到西方和全球南方买家 —— 承担合规、认证、QA 和问责，使采购成为您可以辩护的利润。",
    l1_label: "L1 / 中国深科技采购网关",
    l1_title: "工厂直连西方终端买家，补全缺失的信任层。",
    l1_intro: "中国深科技供应连接到严谨的西方和全球南方买家。Asaptic 通过提供中间商从未提供的信任层赚取利润 —— 供应商尽调、CE / FDA 和目的地市场认证（GCC, INMETRO, SONCAP）、带可选远程视频验厂的 QA 巡检以及负责任的交付。针对出口敏感组件，筛选并提供清洁、非美国 IP 的技术来源。",
    l1_cta: "开始 RFQ →",
    flow_factory: "中国工厂",
    flow_asaptic: "Asaptic 信任 / QA / 合规",
    flow_buyer: "西方终端买家",
    cat_energy: "能源",
    cat_energy_body: "太阳能、BESS 和逆变器。",
    cat_energy_link: "重点关注 UFLPA 可追溯性和 UL 9540A 认证。",
    cat_energy_ev: "EV 充电功率模块 (SiC)",
    cat_medical: "医疗器械",
    cat_medical_body: "由临床权威伙伴和一线医疗照护场景背书的可信采购。",
    cat_components: "深科技组件",
    cat_components_body: "传感器、机器人零件、光子学、功率电子和任务专用组件。",
    l2_label: "L2 / 研发观察名单",
    l2_title: "先贸易，后构建。复合股权。",
    l2_intro: "L2 是长矛：专注于中国深科技领域，采购关系可转化为技术洞察、分销杠杆，并最终转化为产品股权。",
    watch_tfln: "TFLN / LiNbO3 光子学和射频滤波器",
    watch_tfln_body: "第一优先级：用于高速光子学、射频前端和下一代信号基础设施的薄膜铌酸锂。",
    watch_gan: "氮化镓功率",
    watch_gan_body: "用于机器人、能源转换、充电和紧凑型高效系统的宽禁带功率电子。",
    watch_perovskite: "钙钛矿",
    watch_perovskite_body: "可能重塑分布式能源经济的高潜力太阳能材料和制造转型。",
    watch_cooling: "AI 液冷",
    watch_cooling_body: "用于密集 AI 计算、数据中心和边缘部署的热基础设施。",
    watch_sodium: "钠离子电池",
    watch_sodium_body: "用于电网、移动和具有供应链弹性的能源系统的成本敏感型存储化学。",
    watch_lidar: "激光雷达",
    watch_lidar_body: "用于航空、海事、陆地和工业巡检系统的自主感知硬件。",
    authority_label: "权威护城河",
    authority_title: "裹挟在中国执行力中的香港公信力。",
    authority_intro: "护城河不仅是采购渠道。更在于信任/合规层：临床权威、大学和科学园背景，以及为严谨买家打包的国企背景贸易准入。",
    authority_hku: "通过 HKU 关系获得的学术和香港研究背景。",
    authority_hkstp: "科学园信号和深科技生态系统近接性。",
    authority_clinical: "临床权威、老年照护运营和医疗器械买家公信力。",
    engage_label: "参与",
    engage_title: "告诉我们你的需求。我们在四小时内回复。",
    engage_body: "把你的项目、需求和时间表发给我们。我们会给出清晰的路径和具体的下一步。",
    eco_label: "认可与生态",
    eco_title: "香港大学 DeepTech 100 入选初创，孵化于香港科技园。",
    eco_intro: "Asaptic 植根于香港的深科技引擎 —— 入选香港大学 DeepTech 100 计划，并在香港科技园生态中孵化。",
    eco_card1: "香港大学 DeepTech 100",
    eco_card1_desc: "入选香港大学 DeepTech 100 计划 —— 拥有大学科研联结与深科技创始人网络。",
    eco_card2: "香港科技园孵化",
    eco_card2_desc: "在香港科技园生态中孵化 —— 为具身 AI 研发提供工程、实验室与生态支持。",
    engage_cta: "engage@asaptic.com",
    footer_thesis: "论题",
    footer_engage: "参与",
    footer_press: "新闻",
    footer_privacy: "隐私",
    footer_tagline: "中国深科技，以西方级信任交付。",
    footer_tagline_home: "面向空、海、陆的具身自主系统。",
    footer_copy: "© 2026 Asaptic",
    bess_hero_eyebrow: "清洁链能源存储",
    bess_hero_title: "UFLPA 和 UL 9540A：2026 年 BESS 采购标准。",
    bess_hero_sub: "2026 年，从中国采购 BESS 不再仅仅是寻找工厂，而是关于清关和消防安全。Asaptic 提供技术把关，确保高容量 LFP 系统在没有监管扣押的情况下落地。",
    bess_uflpa_label: "UFLPA 可追溯性",
    bess_uflpa_title: "超越“脱敏”提单。",
    bess_uflpa_intro: "CBP 扣押量处于历史高位。美国海关现在要求原材料可追溯至锂矿和石英砂源。我们的“清洁链”协议审核受限地区以外的一线资源，并在发货前提供香港托管文件。",
    bess_cell_title: "A 级电芯验证",
    bess_cell_body: "我们仅采购使用 CATL、BYD 和 EVE 可验证 A 级 LFP 电芯的系统。严禁使用 B 级或回收电芯。",
    bess_safety_title: "UL 9540A 安全",
    bess_safety_body: "经过 NRTL 验证的热失控保护和灭火硬件，满足美国工商业项目许可要求。",
    bess_audit_label: "ASAPTIC 12 点技术审计",

    src_title: "中国硬科技与认证部件采购",
    src_sub: "从经过验证的中国制造商直接供应给西方B2B买家。全套合规文件。由涵盖169个目的市场、854项合规比对的跨标准数据库提供支持。定金锁定产能。六大活跃采购通道——涵盖临床设备、储能系统及物理人工智能 (Physical-AI) 部件。",
    src_tag1: "加拿大卫生部 · TGA认证",
    src_h1: "临床医疗设备",
    src_p1: "专为加拿大和澳大利亚医院及养老机构采购的生物电阻抗及人体成分分析仪。工厂已获MDALL + ARTG验证。独创5步认证采购流程。",
    src_l1: "临床设备采购 →",
    src_tag2: "稀缺供应 · 5天样品交付",
    src_h2: "光子学 — 铌酸锂薄膜 (TFLN)",
    src_p2: "直接从合规的中国晶圆厂采购铌酸锂薄膜晶圆及电光调制器。4英寸及6英寸晶圆现货。样品订单5个工作日内交付。",
    src_l2: "TFLN 采购 →",
    src_tag3: "定金优先 · 30% PI",
    src_h3: "运作模式",
    src_p3: "30% 预付款定金锁定认证工厂的排产排期。见提单 (B/L) 支付尾款。发货时提供全套合规文件。全透明流程——拒绝灰色市场。",
    src_l3: "我们的流程 →",
    src_tag4: "BESS · 逆变器 · EV充电桩",
    src_h4: "能源系统",
    src_p4: "采购自符合UFLPA标准的中国工厂的太阳能逆变器、电池储能系统 (BESS) 及电动汽车充电模块。CE、UL 及 IEC 认证供应链，具备全链路追溯文件，直通西方电网与出行市场。",
    src_l4: "能源系统采购 →",
    src_tag5: "GaN · 钠离子 · 热管理",
    src_h5: "硬科技核心部件",
    src_p5: "从中国硬科技制造集群采购氮化镓 (GaN) 功率电子器件、钠离子电池电芯及先进液冷板热管理模块。是电源转换、新一代储能及高密度计算散热的理想选择。",
    src_l5: "硬科技采购 →",
    src_tag6: "执行器 · 电子皮肤 · 机器人感知",
    src_h6: "物理人工智能与机器人",
    src_p6: "专为具身智能及人形机器人集成商提供的高精度执行器、电子皮肤传感器阵列及机器人感知模块 (RPM)。中国新兴 Physical-AI 部件生态系统工厂直供——已通过西方 OEM 资格审核验证。",
    src_l6: "机器人部件采购 →",
    src_l7: "探索所有采购通道 →",
    src_l8: "工厂直供 vs 贸易公司采购：买家必知 →",
    nav_agents: "智能体",
    agents_portal_cta: "门户 →",
    agents_eyebrow: "ASAPTIC AGENTS — 大中华出海企业 AI 智能体平台",
    agents_title: "注册。合规。融资。全球扩张。",
    agents_sub: "Asaptic Agents 是专为大中华企业出海打造的 AI 智能体平台，覆盖企业全生命周期——从首日注册，到持续合规、政府资助，再到跨境采购与出口。",
    agents_hero_cta: "进入门户 →",
    agents_hero_secondary: "申请早期访问",
    agents_lineup_label: "智能体阵容",
    agents_lineup_title: "一个平台，四大领域，全程覆盖。",
    agents_lineup_intro: "每个智能体专为大中华企业出海生命周期的某一阶段而建。它们共享同一门户、同一记忆和同一合规骨干——让上下文从注册到融资、再到出口自动流转，无缝衔接。",
    agent_form_tag: "注册智能体",
    agent_form_title: "公司注册",
    agent_form_body: "在香港、BVI 或开曼群岛注册实体，选择最优持股架构以支持融资目标，起草公司章程文件，并对接银行账户与注册地址——数日内完成，而非数周。",
    agent_comply_tag: "合规智能体",
    agent_comply_title: "法规合规",
    agent_comply_body: "监控周年申报截止日期、NAR1 申报、税务义务及目的地市场监管要求。自动起草申报文件、提示临近截止日期，并持续更新企业在每个经营司法管辖区的公司记录。",
    agent_fund_tag: "融资智能体 · 已上线",
    agent_fund_title: "研发资助发现",
    agent_fund_body: "每日扫描香港创新科技署、香港生产力局、工业贸易署及其他政府资助计划。将企业档案与开放申请进行匹配，起草申请书并追踪提交截止日期——让您不错过任何资助窗口。",
    agent_fund_link: "在门户中激活 →",
    agent_tender_tag: "招标智能体 · 已上线",
    agent_tender_title: "政府招标响应",
    agent_tender_body: "监控香港政府采购系统 PCMS，筛选匹配招标，根据企业能力评分，并起草完整的投标文件——包括技术、商务和合规章节，全程追踪提交。",
    agent_tender_link: "在门户中激活 →",
    agent_export_tag: "采购出口智能体",
    agent_export_title: "跨境采购与出口",
    agent_export_body: "将您的产品连接到西方及全球南方买家——管理 RFQ 接单、供应商尽调、认证打包（CE、FDA、GCC、INMETRO）、QA 巡检及负责任交付。由 Asaptic 中国深科技采购网关驱动。",
    agent_export_link: "查看采购网关 →",
    agents_flywheel_label: "生命周期飞轮",
    agents_flywheel_title: "每个阶段驱动下一个阶段。",
    agents_flywheel_intro: "Asaptic Agents 将企业生命周期视为一个复合循环——注册开启合规，合规开启融资，融资开启增长，增长开启出口。各智能体跨阶段共享上下文，确保无一环节遗漏。",
    fly_form: "注册",
    fly_form_body: "在正确的司法管辖区注册合适的实体。从第一天起建立完整的公司记录。",
    fly_comply: "合规",
    fly_comply_body: "周年申报、税务申报及目的地市场法规，全部自动追踪并申报。",
    fly_fund: "融资",
    fly_fund_body: "持续发现、匹配、起草并提交政府资助与招标申请。",
    fly_grow: "全球扩张",
    fly_grow_body: "产品通过全合规、全 QA 的流程，出口至西方及全球南方市场。",
    agents_live_label: "已上线",
    agents_live_title: "两个智能体已在运行，更多正在路上。",
    agents_live_intro: "研发融资智能体与招标智能体已在 Asaptic 门户中投入运营。它们每日自动扫描、起草响应并推送匹配结果——无需人工监控。",
    live_fund_label: "研发资助",
    live_fund_body: "每日扫描香港创新科技署、生产力局、工业贸易署及相关资助计划。自动匹配并起草申请。",
    live_tender_label: "PCMS 招标",
    live_tender_body: "监控香港政府 PCMS 采购系统，评分匹配度，起草完整投标文件包。",
    live_portal_label: "门户访问",
    live_portal_body: "所有智能体均通过 portal.asaptic.com 运行。尚未纳入门户的智能体可申请早期访问。",
    agents_cta_label: "立即开始",
    agents_cta_title: "让智能体运行您的企业全生命周期。",
    agents_cta_body: "进入门户激活已上线的智能体，或联系我们探讨为您的大中华企业定制部署方案。",
    agents_cta_portal: "进入门户 →",
    agents_cta_email: "engage@asaptic.com",
  },
  zht: {
    nav_physical: "物理 AI",
    nav_sourcing: "採購",
    nav_watchlist: "觀察名單",
    nav_engage: "參與",
    nav_blog: "博客",
    nav_cta: "聯繫我們",
    hero_eyebrow: "物理 AI · 無人機 / 海事 / 機器人",
    hero_title: "為無人機、海事和機器人打造的物理 AI。",
    hero_sub: "Asaptic 跨越空、海、陸三域構建具身自主系統 —— 包括 HK300 重載無人共軸直升機平台、自主海事船隻和陸地機器人。香港大學 DeepTech 100 入選初創，孵化於香港科技園生態。",
    hero_primary: "與我們合作",
    hero_secondary: "查看領域",
    hero_panel_status: "系統地圖已激活",
    map_aerial: "航空",
    map_marine: "海事",
    map_ground: "陸地",
    metric_weight: "300kg",
    metric_weight_label: "HK300 已驗證平台",
    metric_domains: "3",
    metric_domains_label: "物理領域",
    metric_response: "<4h",
    metric_response_label: "響應承諾",
    physical_label: "L0 / 物理 AI 前沿",
    physical_title: "空、海、陸三域的具身自主。",
    physical_intro: "Asaptic 為在現實世界中運行的自主機器構建控制、部署與信任層——貫穿空、海、陸的具身智能。",
    aerial_tag: "航空系統",
    aerial_heading: "重載無人共軸直升機和無人機。",
    aerial_body: "航空領域始於 HK300：一個經過驗證的 300 公斤級重載無人共軸直升機平台，用於工業載荷、野外物流和任務專用自主系統。",
    aerial_spec1: "HK300",
    aerial_spec2: "共軸 / 無人",
    marine_tag: "海事自主",
    marine_heading: "自主水面和水下船隻。",
    marine_body: "海事系統將同樣的具身 AI 技術棧延伸到水面和水下的巡檢、環境監測、港口運營和長航時任務。",
    marine_spec1: "USV / UUV",
    marine_spec2: "導航 / 傳感",
    ground_tag: "陸地機器人",
    ground_heading: "用於物流、巡檢和野外工作的機器人。",
    ground_body: "陸地機器人閉合了物理環路：移動性、操作性、感知、車隊編排以及針對軟件無法行動的現場提供人類監督的自主性。",
    ground_spec1: "移動機器人",
    ground_spec2: "車隊運營",
    srcpage_eyebrow: "中國深科技採購網關",
    srcpage_title: "中國深科技與世界之間的信任層。",
    srcpage_sub: "Asaptic 將工廠直接連接到西方和全球南方買家 —— 承擔合規、認證、QA 和問責，使採購成為您可以辯護的利潤。",
    l1_label: "L1 / 中國深科技採購網關",
    l1_title: "工廠直連西方終端買家，補全缺失的信任層。",
    l1_intro: "中國深科技供應連接到嚴謹的西方和全球南方買家。Asaptic 通過提供中間商從未提供的信任層賺取利潤 —— 供應商盡調、CE / FDA 和目的地市場認證（GCC, INMETRO, SONCAP）、帶可选遠程視頻驗廠的 QA 巡檢以及負責任的交付。針對出口敏感組件，篩選並提供清潔、非美國 IP 的技術來源。",
    l1_cta: "開始 RFQ →",
    flow_factory: "中國工廠",
    flow_asaptic: "Asaptic 信任 / QA / 合規",
    flow_buyer: "西方終端買家",
    cat_energy: "能源",
    cat_energy_body: "太陽能、BESS 和逆變器。",
    cat_energy_link: "重點關注 UFLPA 可追溯性和 UL 9540A 認證。",
    cat_energy_ev: "EV 充電功率模組 (SiC)",
    cat_medical: "醫療器械",
    cat_medical_body: "由臨床權威夥伴和一線醫療照護場景背書的可信採購。",
    cat_components: "深科技組件",
    cat_components_body: "傳感器、機器人零件、光子學、功率電子和任務專用組件。",
    l2_label: "L2 / 研發觀察名單",
    l2_title: "先貿易，後構建。複合股權。",
    l2_intro: "L2 是長矛：專注於中國深科技領域，採購關係可轉化為技術洞察、分銷杠桿，並最終轉化為產品股權。",
    watch_tfln: "TFLN / LiNbO3 光子學和射頻濾波器",
    watch_tfln_body: "第一優先級：用於高速光子學、射頻前端和下一代信號基礎設施的薄膜鈮酸鋰。",
    watch_gan: "氮化傢功率",
    watch_gan_body: "用於機器人、能源轉換、充電和緊湊型高效系統的寬禁帶功率電子。",
    watch_perovskite: "鈣鈦礦",
    watch_perovskite_body: "可能重塑分佈式能源經濟的高潛力太陽能材料和製造轉型。",
    watch_cooling: "AI 液冷",
    watch_cooling_body: "用於密集 AI 計算、數據中心和邊緣部署的热基礎設施。",
    watch_sodium: "鈉離子電池",
    watch_sodium_body: "用於電網、移動和具有供應鏈彈性的能源系統的成本敏感型存儲化學。",
    watch_lidar: "激光雷達",
    watch_lidar_body: "用於航空、海事、陸地和工業巡檢系統的自主感知硬件。",
    authority_label: "權威護城河",
    authority_title: "裹挾在中國執行力中的香港公信力。",
    authority_intro: "護城河不僅是採購渠道。更在於信任/合規層：臨床權威、大學和科學園背景，以及為嚴謹買家打包的國企背景貿易准入。",
    authority_hku: "通過 HKU 關係獲得的學術和香港研究背景。",
    authority_hkstp: "科學園信號和深科技生態系統近接性。",
    authority_clinical: "臨床權威、老年照護運營和醫療器械買家公信力。",
    engage_label: "參與",
    engage_title: "告訴我們你的需求。我們在四小時內回覆。",
    engage_body: "把你的項目、需求和時間表發給我們。我們會給出清晰的路徑和具體的下一步。",
    eco_label: "認可與生態",
    eco_title: "香港大學 DeepTech 100 入選初創，孵化於香港科技園。",
    eco_intro: "Asaptic 植根於香港的深科技引擎 —— 入選香港大學 DeepTech 100 計劃，並在香港科技園生態中孵化。",
    eco_card1: "香港大學 DeepTech 100",
    eco_card1_desc: "入選香港大學 DeepTech 100 計劃 —— 擁有大學科研聯結與深科技創始人網絡。",
    eco_card2: "香港科技園孵化",
    eco_card2_desc: "在香港科技園生態中孵化 —— 為具身 AI 研發提供工程、實驗室與生態支持。",
    engage_cta: "engage@asaptic.com",
    footer_thesis: "論題",
    footer_engage: "參與",
    footer_press: "新聞",
    footer_privacy: "隱私",
    footer_tagline: "中國深科技，以西方級信任交付。",
    footer_tagline_home: "面向空、海、陸的具身自主系統。",
    footer_copy: "© 2026 Asaptic",
    bess_hero_eyebrow: "清潔鏈能源存儲",
    bess_hero_title: "UFLPA 和 UL 9540A：2026 年 BESS 採購標準。",
    bess_hero_sub: "2026 年，從中國採購 BESS 不再僅等同於尋找工廠，而是關於清關和消防安全。Asaptic 提供技術把關，確保高容量 LFP 系統在沒有監管扣押的情況下落地。",
    bess_uflpa_label: "UFLPA 可追溯性",
    bess_uflpa_title: "超越「脫敏」提單。",
    bess_uflpa_intro: "CBP 扣押量處於歷史高位。美國海關現在要求原材料可追溯至鋰礦和石英砂源。我們的「清潔鏈」協議審核受限地區以外的一線資源，並在發貨前提供香港託管文件。",
    bess_cell_title: "A 級電芯驗證",
    bess_cell_body: "我們僅採購使用 CATL、BYD 和 EVE 可驗證 A 級 LFP 電芯的系統。嚴禁使用 B 級或回收電芯。",
    bess_safety_title: "UL 9540A 安全",
    bess_safety_body: "經過 NRTL 驗證的热失控保護和滅火硬件，滿足美國工商業項目許可要求。",
    bess_audit_label: "ASAPTIC 12 點技術審計",
    src_title: "中國硬科技與認證部件採購",
    src_sub: "從經過驗證的中國製造商直接供應給西方B2B買家。全套合規文件。由涵蓋169個目的市場、854項合規比對的跨標準數據庫提供支持。定金鎖定產能。六大活躍採購通道——涵蓋臨床設備、儲能系統及物理人工智慧 (Physical-AI) 部件。",
    src_tag1: "加拿大衛生部 · TGA認證",
    src_h1: "臨床醫療設備",
    src_p1: "專為加拿大和澳大利亞醫院及養老機構採購的生物電阻抗及人體成分分析儀。工廠已獲MDALL + ARTG驗證。獨創5步認證採購流程。",
    src_l1: "臨床設備採購 →",
    src_tag2: "稀缺供應 · 5天樣品交付",
    src_h2: "光子學 — 鈮酸鋰薄膜 (TFLN)",
    src_p2: "直接從合規的中國晶圓廠採購鈮酸鋰薄膜晶圓及電光調製器。4英吋及6英吋晶圓現貨。樣品訂單5個工作日內交付。",
    src_l2: "TFLN 採購 →",
    src_tag3: "定金優先 · 30% PI",
    src_h3: "運作模式",
    src_p3: "30% 預付款定金鎖定認證工廠的排產排期。見提單 (B/L) 支付尾款。發貨時提供全套合規文件。全透明流程——拒絕灰色市場。",
    src_l3: "我們的流程 →",
    src_tag4: "BESS · 逆變器 · EV充電樁",
    src_h4: "能源系統",
    src_p4: "採購自符合UFLPA標準的中國工廠的太陽能逆變器、電池儲能系統 (BESS) 及電動汽車充電模組。CE、UL 及 IEC 認證供應鏈，具備全鏈路追溯文件，直通西方電網與出行市場。",
    src_l4: "能源系統採購 →",
    src_tag5: "GaN · 鈉離子 · 熱管理",
    src_h5: "硬科技核心部件",
    src_p5: "從中國硬科技製造集群採購氮化鎵 (GaN) 功率電子器件、鈉離子電池電芯及先進液冷板熱管理模組。是電源轉換、新一代儲能及高密度計算散熱的理想選擇。",
    src_l5: "硬科技採購 →",
    src_tag6: "執行器 · 電子皮膚 · 機器人感知",
    src_h6: "物理人工智慧與機器人",
    src_p6: "專為具身智能及人形機器人集成商提供的高精度執行器、電子皮膚傳感器陣列及機器人感知模組 (RPM)。中國新興 Physical-AI 部件生態系統工廠直供——已通過西方 OEM 資格審核驗證。",
    src_l6: "機器人部件採購 →",
    src_l7: "探索所有採購通道 →",
    src_l8: "工廠直供 vs 貿易公司採購：買家必知 →",
    nav_agents: "智能代理",
    agents_portal_cta: "門戶 →",
    agents_eyebrow: "ASAPTIC AGENTS — 大中華出海企業 AI 智能代理平台",
    agents_title: "註冊。合規。融資。全球擴張。",
    agents_sub: "Asaptic Agents 是專為大中華企業出海打造的 AI 智能代理平台，覆蓋企業全生命週期——從首日註冊，到持續合規、政府資助，再到跨境採購與出口。",
    agents_hero_cta: "進入門戶 →",
    agents_hero_secondary: "申請早期使用",
    agents_lineup_label: "智能代理陣容",
    agents_lineup_title: "一個平台，四大領域，全程覆蓋。",
    agents_lineup_intro: "每個智能代理專為大中華企業出海生命週期的某一階段而建。它們共享同一門戶、同一記憶和同一合規骨幹——讓上下文從註冊到融資、再到出口自動流轉，無縫銜接。",
    agent_form_tag: "註冊代理",
    agent_form_title: "公司註冊",
    agent_form_body: "在香港、BVI 或開曼群島註冊實體，選擇最優持股架構以支持融資目標，起草公司章程文件，並對接銀行賬戶與註冊地址——數日內完成，而非數週。",
    agent_comply_tag: "合規代理",
    agent_comply_title: "法規合規",
    agent_comply_body: "監控周年申報截止日期、NAR1 申報、稅務義務及目的地市場監管要求。自動起草申報文件、提示臨近截止日期，並持續更新企業在每個經營司法管轄區的公司記錄。",
    agent_fund_tag: "融資代理 · 已上線",
    agent_fund_title: "研發資助發現",
    agent_fund_body: "每日掃描香港創新科技署、香港生產力局、工業貿易署及其他政府資助計劃。將企業檔案與開放申請進行匹配，起草申請書並追蹤提交截止日期——讓您不錯過任何資助窗口。",
    agent_fund_link: "在門戶中激活 →",
    agent_tender_tag: "招標代理 · 已上線",
    agent_tender_title: "政府招標響應",
    agent_tender_body: "監控香港政府採購系統 PCMS，篩選匹配招標，根據企業能力評分，並起草完整的投標文件——包括技術、商務和合規章節，全程追蹤提交。",
    agent_tender_link: "在門戶中激活 →",
    agent_export_tag: "採購出口代理",
    agent_export_title: "跨境採購與出口",
    agent_export_body: "將您的產品連接到西方及全球南方買家——管理 RFQ 接單、供應商盡調、認證打包（CE、FDA、GCC、INMETRO）、QA 巡檢及負責任交付。由 Asaptic 中國深科技採購網關驅動。",
    agent_export_link: "查看採購網關 →",
    agents_flywheel_label: "生命週期飛輪",
    agents_flywheel_title: "每個階段驅動下一個階段。",
    agents_flywheel_intro: "Asaptic Agents 將企業生命週期視為一個複合循環——註冊開啟合規，合規開啟融資，融資開啟增長，增長開啟出口。各智能代理跨階段共享上下文，確保無一環節遺漏。",
    fly_form: "註冊",
    fly_form_body: "在正確的司法管轄區註冊合適的實體。從第一天起建立完整的公司記錄。",
    fly_comply: "合規",
    fly_comply_body: "周年申報、稅務申報及目的地市場法規，全部自動追蹤並申報。",
    fly_fund: "融資",
    fly_fund_body: "持續發現、匹配、起草並提交政府資助與招標申請。",
    fly_grow: "全球擴張",
    fly_grow_body: "產品通過全合規、全 QA 的流程，出口至西方及全球南方市場。",
    agents_live_label: "已上線",
    agents_live_title: "兩個智能代理已在運行，更多正在路上。",
    agents_live_intro: "研發融資代理與招標代理已在 Asaptic 門戶中投入運營。它們每日自動掃描、起草響應並推送匹配結果——無需人工監控。",
    live_fund_label: "研發資助",
    live_fund_body: "每日掃描香港創新科技署、生產力局、工業貿易署及相關資助計劃。自動匹配並起草申請。",
    live_tender_label: "PCMS 招標",
    live_tender_body: "監控香港政府 PCMS 採購系統，評分匹配度，起草完整投標文件包。",
    live_portal_label: "門戶使用",
    live_portal_body: "所有智能代理均通過 portal.asaptic.com 運行。尚未納入門戶的代理可申請早期使用。",
    agents_cta_label: "立即開始",
    agents_cta_title: "讓智能代理運行您的企業全生命週期。",
    agents_cta_body: "進入門戶激活已上線的智能代理，或聯繫我們探討為您的大中華企業定制部署方案。",
    agents_cta_portal: "進入門戶 →",
    agents_cta_email: "engage@asaptic.com",
  },
  pt: {
    nav_physical: "IA Física",
    nav_sourcing: "Sourcing",
    nav_watchlist: "Watchlist",
    nav_engage: "Envolver",
    nav_blog: "Blog",
    nav_cta: "Contacto",
    hero_eyebrow: "IA FÍSICA · DRONE / MARINHA / ROBÔ",
    hero_title: "IA Física para drones, marinha e robôr.",
    hero_sub: "A Asaptic constrói sistemas autónomos incorporados em três domínios — aéreo, marinho e terrestre — incluindo a plataforma de helicóptero coaxial não tripulado HK300 para cargas pesadas, embarcações marinhas autónomas e robôs terrestres. Uma startup do programa HKU DeepTech 100, incubada no ecossistema HKSTP.",
    hero_primary: "Trabalhe connosco",
    hero_secondary: "Ver domínios",
    hero_panel_status: "MAPA DE SISTEMAS ATIVO",
    map_aerial: "Aéreo",
    map_marine: "Marinho",
    map_ground: "Terrestre",
    metric_weight: "300kg",
    metric_weight_label: "Plataforma validada HK300",
    metric_domains: "3",
    metric_domains_label: "domínios físicos",
    metric_response: "<4h",
    metric_response_label: "promessa de resposta",
    physical_label: "L0 / FRONTEIRA DA IA FÍSICA",
    physical_title: "Autonomia incorporada no ar, mar e terra.",
    physical_intro: "A Asaptic constrói a camada de controlo, implementação e confiança para máquinas autónomas que operam no mundo real — inteligência incorporada no ar, no mar e em terra.",
    aerial_tag: "SISTEMAS AÉREOS",
    aerial_heading: "Helicópteros coaxiais não tripulados e drones para cargas pesadas.",
    aerial_body: "O domínio aéreo começa com o HK300: uma plataforma de helicóptero coaxial não tripulado de 300kg validada para cargas industriais, logística de campo e autonomia especializada em missões.",
    aerial_spec1: "HK300",
    aerial_spec2: "coaxial / não tripulado",
    marine_tag: "AUTONOMIA MARINHA",
    marine_heading: "Embarcações de superfície e subaquáticas autónomas.",
    marine_body: "Os sistemas marinhos estendem a mesma stack de IA incorporada para inspeção, monitorização ambiental, operações portuárias e missões de resistência acima e abaixo da superfície.",
    marine_spec1: "USV / UUV",
    marine_spec2: "navegação / deteção",
    ground_tag: "ROBÔS TERRESTRES",
    ground_heading: "Robôs para logística, inspeção e trabalho de campo.",
    ground_body: "Os robôs terrestres fecham o ciclo físico: mobilidade, manipulação, perceção, orquestração de frotas e autonomia supervisionada por humanos para locais onde o software sozinho não pode atuar.",
    ground_spec1: "robôs móveis",
    ground_spec2: "operações de frota",
    srcpage_eyebrow: "GATEWAY DE SOURCING DEEP-TECH DA CHINA",
    srcpage_title: "A camada de confiança entre a deep-tech da China e o mundo.",
    srcpage_sub: "A Asaptic liga as fábricas diretamente aos compradores ocidentais e do Sul Global — com a conformidade, certificação, QA e responsabilidade que torna o sourcing numa margem defensável.",
    l1_label: "L1 / GATEWAY DE SOURCING DEEP-TECH DA CHINA",
    l1_title: "Da fábrica diretamente para o comprador final ocidental, com a camada de confiança que faltava.",
    l1_intro: "Fornecimento deep-tech da China ligado a compradores ocidentais e do Sul Global sérios. A Asaptic ganha a margem ao fornecer a camada de confiança que os intermediários nunca deram — diligência do fornecedor, certificação CE / FDA e do mercado de destino (GCC, INMETRO, SONCAP), inspeção de QA com verificação visual opcional da fábrica e entrega responsável. Para componentes sensíveis à exportação, o fornecimento é rastreado para uma origem tecnológica limpa, sem IP dos EUA.",
    l1_cta: "Iniciar um RFQ →",
    flow_factory: "Fábrica na China",
    flow_asaptic: "Asaptic confiança / QA / conformidade",
    flow_buyer: "Comprador final ocidental",
    cat_energy: "Energia",
    cat_energy_body: "Solar, BESS e inversores. ",
    cat_energy_link: "Foco na rastreabilidade UFLPA e certificação UL 9540A.",
    cat_energy_ev: "Módulos de potência para carregadores EV (SiC)",
    cat_medical: "Dispositivos médicos",
    cat_medical_body: "Sourcing clinicamente credível apoiado por um parceiro de autoridade clínica e contexto de cuidados de saúde na linha da frente.",
    cat_components: "Componentes deep-tech",
    cat_components_body: "Sensores, peças de robótica, fotónica, eletrónica de potência e conjuntos específicos de missão.",
    l2_label: "L2 / WATCHLIST DE R&D",
    l2_title: "Negociar agora. Construir depois. Capitalizar o equity.",
    l2_intro: "L2 é a lança: uma watchlist focada em campos deep-tech da China onde as relações de sourcing se podem tornar em insights técnicos, alavancagem de distribuição e, eventualmente, equity de produto.",
    watch_tfln: "Fotónica TFLN / LiNbO3 e filtros RF",
    watch_tfln_body: "Prioridade número um: niobato de lítio de película fina para fotónica de alta velocidade, front-ends de RF e infraestrutura de sinal de próxima geração.",
    watch_gan: "Potência GaN",
    watch_gan_body: "Eletrónica de potência de banda larga para robótica, conversão de energia, carregamento e sistemas compactos de alta eficiência.",
    watch_perovskite: "Perovskita",
    watch_perovskite_body: "Materiais solares de alto potencial e transições de fabrico que podem remodelar a economia da energia distribuída.",
    watch_cooling: "Arrefecimento líquido de IA",
    watch_cooling_body: "Infraestrutura térmica para computação densa de IA, centros de dados e implementações de edge.",
    watch_sodium: "Baterias de ião de sódio",
    watch_sodium_body: "Química de armazenamento sensível ao custo para redes, mobilidade e sistemas de energia resilientes à cadeia de fornecimento.",
    watch_lidar: "LiDAR",
    watch_lidar_body: "Hardware de perceção para autonomia em sistemas aéreos, marinhos, terrestres e de inspeção industrial.",
    authority_label: "MOAT DE AUTORIDADE",
    authority_title: "Credibilidade de Hong Kong envolta na execução da China.",
    authority_intro: "A defensibilidade não é apenas o acesso ao sourcing. É a camada de confiança/conformidade: autoridade clínica, contexto universitário e de parques científicos, e acesso comercial afiliado ao Estado embalado para compradores sérios.",
    authority_hku: "Contexto académico e de investigação em Hong Kong através de relações com a HKU.",
    authority_hkstp: "Sinal de parque científico e proximidade do ecossistema deep-tech.",
    authority_clinical: "Autoridade clínica, operações de cuidados a idosos e credibilidade perante compradores de dispositivos médicos.",
    engage_label: "ENVOLVER",
    engage_title: "Diga-nos o que precisa. Respondemos em menos de quatro horas.",
    engage_body: "Envie-nos o seu projeto, requisitos e cronograma. Responderemos com um caminho claro e o próximo passo concreto.",
    eco_label: "RECONHECIMENTO E ECOSSISTEMA",
    eco_title: "Uma startup HKU DeepTech 100, incubada na HKSTP.",
    eco_intro: "A Asaptic é construída dentro do motor deep-tech de Hong Kong — selecionada para o programa DeepTech 100 da Universidade de Hong Kong e incubada no ecossistema dos Parques de Ciência e Tecnologia de Hong Kong.",
    eco_card1: "HKU DeepTech 100",
    eco_card1_desc: "Selecionada para o programa DeepTech 100 da Universidade de Hong Kong — ligação à investigação universitária e uma rede de fundadores deep-tech.",
    eco_card2: "Incubação HKSTP",
    eco_card2_desc: "Incubada no ecossistema dos Parques de Ciência e Tecnologia de Hong Kong — apoio de engenharia, laboratório e ecossistema para o desenvolvimento de IA incorporada.",
    engage_cta: "engage@asaptic.com",
    footer_thesis: "Tese",
    footer_engage: "Envolver",
    footer_press: "Imprensa",
    footer_privacy: "Privacidade",
    footer_tagline: "Deep-tech da China, com confiança de padrão ocidental.",
    footer_tagline_home: "Sistemas autónomos incorporados para ar, mar e terra.",
    footer_copy: "© 2026 Asaptic"
  }
};
